import { useCallback, useState } from 'react';
import { useFocusEffect, useRouter } from 'expo-router';
import { FlatList, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { AuthRequired } from '@/components/auth-required';
import { mobileApi } from '@/api';
type Domain = { domain:string; reviewed:number; explainable:number; unclear:number };

export default function ProgressScreen() { return <AuthRequired><ProgressContent /></AuthRequired>; }
function ProgressContent() {
  const router=useRouter(); const [stats,setStats]=useState({explainable:0,unclear:0}); const [domains,setDomains]=useState<Domain[]>([]); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const data=await mobileApi.dashboard();setStats(data.stats);setDomains(data.domains);}catch(reason){setError(reason instanceof Error?reason.message:'Could not load progress.');}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{void load();},[load])); const total=stats.explainable+stats.unclear;
  return <SafeAreaView style={styles.safeArea}><FlatList data={domains} keyExtractor={(item)=>item.domain} contentContainerStyle={styles.content} ListHeaderComponent={<View><Text style={styles.kicker}>Learning progress</Text><Text style={styles.title}>Progress</Text><View style={styles.summary}><Metric label="Explainable" value={stats.explainable}/><Metric label="Unclear" value={stats.unclear}/><Metric label="Reviewed" value={total}/></View>{error?<Text style={styles.error}>{error}</Text>:null}{loading?<Text style={styles.sub}>Loading…</Text>:null}</View>} ListEmptyComponent={!loading?<View style={styles.empty}><Text style={styles.emptyTitle}>No progress yet</Text><Text style={styles.sub}>Practice cards to see your domain breakdown.</Text><Pressable onPress={()=>router.push('/(tabs)/practice')} style={styles.primary}><Text style={styles.primaryText}>Practice now</Text></Pressable></View>:null} renderItem={({item})=>{const percent=item.reviewed?Math.round(item.explainable/item.reviewed*100):0;return <View style={styles.domain}><View style={styles.row}><Text style={styles.domainTitle}>{item.domain}</Text><Text style={styles.percent}>{percent}%</Text></View><Text style={styles.sub}>{item.reviewed} reviewed · {item.explainable} explainable · {item.unclear} unclear</Text><View style={styles.track}><View style={[styles.fill,{width:`${percent}%`}]}/></View></View>}}/></SafeAreaView>;
}
function Metric({label,value}:{label:string;value:number}){return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>}
const styles=StyleSheet.create({safeArea:{flex:1,backgroundColor:'#f7f8fb'},content:{padding:20,paddingBottom:32,gap:12},kicker:{color:'#47606f',fontSize:13,fontWeight:'800',textTransform:'uppercase'},title:{color:'#111827',fontSize:32,fontWeight:'800',marginBottom:14},summary:{flexDirection:'row',gap:8,marginBottom:14},metric:{flex:1,backgroundColor:'#fff',borderRadius:10,padding:12},metricValue:{fontSize:24,fontWeight:'800',color:'#111827'},metricLabel:{fontSize:12,fontWeight:'700',color:'#607080',marginTop:3},sub:{color:'#607080',fontSize:14,lineHeight:21},error:{color:'#b91c1c',marginBottom:8},domain:{backgroundColor:'#fff',padding:16,borderRadius:12,gap:8},row:{flexDirection:'row',justifyContent:'space-between',gap:12},domainTitle:{color:'#111827',fontSize:16,fontWeight:'800',flex:1},percent:{color:'#2563eb',fontWeight:'800'},track:{height:8,backgroundColor:'#e5e7eb',borderRadius:8,overflow:'hidden'},fill:{height:8,backgroundColor:'#22c55e',borderRadius:8},empty:{backgroundColor:'#fff',borderRadius:12,padding:24,alignItems:'center',gap:8,marginTop:10},emptyTitle:{color:'#111827',fontWeight:'800',fontSize:18},primary:{backgroundColor:'#111827',borderRadius:8,paddingHorizontal:16,paddingVertical:12,marginTop:8},primaryText:{color:'#fff',fontWeight:'800'}});
