export const EXTRA_MESSAGES = {
  en: {
    "nav.knowledgeInbox": "Knowledge Inbox", "nav.adminOps": "Monitoring Ops",
    "admin.ops": "Capacity",
    "ads.cardAria": "Sponsored practice card", "ads.sponsored": "Sponsored", "ads.afterCards": "After {count} cards", "ads.title": "Stay in your review flow.", "ads.body": "Unlock the full public map and remove sponsored cards with Girapphe Plus. Your private concepts stay free.", "ads.plans": "See Girapphe Plus", "ads.continue": "Continue reviewing",
    "toss.failTitle": "Card registration was cancelled", "toss.failBody": "No payment or subscription access was created.", "toss.back": "Back to subscriptions", "toss.startError": "Toss recurring billing could not start. Check your sign-in and configuration.", "toss.opening": "Opening Toss checkout…", "toss.manageFirst": "Manage your current subscription first", "toss.trialButton": "14-day trial with a Korean card · then ₩{amount}", "toss.payButton": "Pay ₩{amount} with a Korean card", "toss.supportedCards": "Only Korean-issued cards enabled for Toss recurring billing are supported. The billing period and KRW amount appear on the confirmation screen.",
    "inbox.eyebrow": "Private review queue", "inbox.title": "Knowledge Inbox", "inbox.subtitle": "Review concept drafts explicitly sent from a current connected AI conversation. Nothing is added to your map until you approve it.", "inbox.pendingBatches": "pending batches", "inbox.boundaryTitle": "Approval boundary:", "inbox.boundaryBody": "each row is one explicitly sent batch. Add all applies only to that batch, never to older conversations or future messages.", "inbox.cardsAdded": "{count} cards added.", "inbox.edgesSkipped": "{count} relationship suggestions were skipped because their targets were unavailable, duplicated, or would create an invalid cycle.", "inbox.edgesSaved": "All approved relationships were saved.", "inbox.emptyTitle": "No drafts waiting", "inbox.emptyBody": "Send selected concepts from a current AI conversation, then return here to review them.", "inbox.manualNote": "Add a manual note instead", "inbox.drafts": "{count} drafts", "inbox.requested": "Requested: {mode}", "inbox.currentImport": "Current conversation import", "inbox.isolated": "This review is isolated to batch", "inbox.sourceReference": "Source reference: {reference}", "inbox.received": "Received {date}", "inbox.reviewBatch": "Review this batch", "inbox.back": "Back to Knowledge Inbox", "inbox.reviewTitle": "Review knowledge drafts", "inbox.reviewSubtitle": "Edit content and relationships before adding cards to your private graph."
  },
  ja: {
    "nav.knowledgeInbox": "ナレッジ受信箱", "nav.adminOps": "運用モニタリング",
    "admin.ops": "容量",
    "ads.cardAria": "スポンサー付き練習カード", "ads.sponsored": "スポンサー", "ads.afterCards": "{count}枚のカードの後", "ads.title": "復習の流れを保ちましょう。", "ads.body": "Girapphe Plusで公開マップ完全版を開き、スポンサー表示を削除できます。非公開概念は無料のままです。", "ads.plans": "Girapphe Plusを見る", "ads.continue": "復習を続ける",
    "toss.failTitle": "カード登録がキャンセルされました", "toss.failBody": "決済も購読権限も作成されていません。", "toss.back": "購読画面に戻る", "toss.startError": "Tossの定期決済を開始できません。ログインと設定を確認してください。", "toss.opening": "Toss決済画面を開いています…", "toss.manageFirst": "先に現在の購読を管理してください", "toss.trialButton": "韓国発行カードで14日間無料 · 以後₩{amount}", "toss.payButton": "韓国発行カードで₩{amount}を支払う", "toss.supportedCards": "Toss定期決済が有効な韓国発行カードのみ対応します。請求周期とウォン金額は確認画面に表示されます。",
    "inbox.eyebrow": "非公開レビューキュー", "inbox.title": "ナレッジ受信箱", "inbox.subtitle": "現在接続中のAI会話から明示的に送られた概念の下書きを確認します。承認するまでマップには追加されません。", "inbox.pendingBatches": "保留中のバッチ", "inbox.boundaryTitle": "承認範囲：", "inbox.boundaryBody": "各行は明示的に送られた1バッチです。すべて追加はそのバッチだけに適用されます。", "inbox.cardsAdded": "{count}枚のカードを追加しました。", "inbox.edgesSkipped": "対象なし、重複、無効な循環のため{count}件の関係候補を除外しました。", "inbox.edgesSaved": "承認した関係をすべて保存しました。", "inbox.emptyTitle": "待機中の下書きはありません", "inbox.emptyBody": "現在のAI会話から概念を送信し、ここで確認してください。", "inbox.manualNote": "代わりに手動メモを追加", "inbox.drafts": "下書き{count}件", "inbox.requested": "要求：{mode}", "inbox.currentImport": "現在の会話のインポート", "inbox.isolated": "このレビューの対象バッチ", "inbox.sourceReference": "参照元：{reference}", "inbox.received": "受信 {date}", "inbox.reviewBatch": "このバッチを確認", "inbox.back": "ナレッジ受信箱に戻る", "inbox.reviewTitle": "ナレッジ下書きを確認", "inbox.reviewSubtitle": "非公開グラフに追加する前に内容と関係を編集します。"
  },
  "zh-CN": {
    "nav.knowledgeInbox": "知识收件箱", "nav.adminOps": "监控运维",
    "admin.ops": "容量",
    "ads.cardAria": "赞助练习卡", "ads.sponsored": "赞助", "ads.afterCards": "完成{count}张卡片后", "ads.title": "保持你的复习节奏。", "ads.body": "使用 Girapphe Plus 解锁完整公开图谱并移除赞助卡。你的私密概念始终免费。", "ads.plans": "查看 Girapphe Plus", "ads.continue": "继续复习",
    "toss.failTitle": "银行卡注册已取消", "toss.failBody": "未产生付款或订阅权限。", "toss.back": "返回订阅页面", "toss.startError": "无法启动Toss定期付款。请检查登录和配置。", "toss.opening": "正在打开Toss付款窗口…", "toss.manageFirst": "请先管理当前订阅", "toss.trialButton": "韩国银行卡免费试用14天 · 之后₩{amount}", "toss.payButton": "使用韩国银行卡支付₩{amount}", "toss.supportedCards": "仅支持已启用Toss定期付款的韩国发行银行卡。确认页面会显示计费周期和韩元金额。",
    "inbox.eyebrow": "私密审核队列", "inbox.title": "知识收件箱", "inbox.subtitle": "审核从当前已连接AI对话中明确发送的概念草稿。只有批准后才会加入知识图谱。", "inbox.pendingBatches": "待处理批次", "inbox.boundaryTitle": "批准范围：", "inbox.boundaryBody": "每行都是一个明确发送的批次。全部添加只应用于该批次。", "inbox.cardsAdded": "已添加{count}张卡片。", "inbox.edgesSkipped": "因目标不可用、重复或会形成无效循环，已跳过{count}条关系建议。", "inbox.edgesSaved": "所有已批准关系均已保存。", "inbox.emptyTitle": "没有待审核草稿", "inbox.emptyBody": "从当前AI对话发送所选概念，然后返回这里审核。", "inbox.manualNote": "改为手动添加笔记", "inbox.drafts": "{count}份草稿", "inbox.requested": "请求：{mode}", "inbox.currentImport": "当前对话导入", "inbox.isolated": "本次审核仅限批次", "inbox.sourceReference": "来源引用：{reference}", "inbox.received": "接收于{date}", "inbox.reviewBatch": "审核此批次", "inbox.back": "返回知识收件箱", "inbox.reviewTitle": "审核知识草稿", "inbox.reviewSubtitle": "加入私密知识图谱前编辑内容和关系。"
  },
  es: {
    "nav.knowledgeInbox": "Bandeja de conocimiento", "nav.adminOps": "Operaciones de monitoreo",
    "admin.ops": "Capacidad",
    "ads.cardAria": "Tarjeta de práctica patrocinada", "ads.sponsored": "Patrocinado", "ads.afterCards": "Después de {count} tarjetas", "ads.title": "Mantén tu ritmo de repaso.", "ads.body": "Desbloquea el mapa público completo y elimina las tarjetas patrocinadas con Girapphe Plus. Tus conceptos privados siguen siendo gratis.", "ads.plans": "Ver Girapphe Plus", "ads.continue": "Continuar repasando",
    "toss.failTitle": "Se canceló el registro de la tarjeta", "toss.failBody": "No se creó ningún pago ni acceso de suscripción.", "toss.back": "Volver a suscripciones", "toss.startError": "No se pudo iniciar el pago recurrente de Toss. Comprueba tu sesión y configuración.", "toss.opening": "Abriendo el pago de Toss…", "toss.manageFirst": "Gestiona primero tu suscripción actual", "toss.trialButton": "14 días gratis con tarjeta coreana · después ₩{amount}", "toss.payButton": "Pagar ₩{amount} con tarjeta coreana", "toss.supportedCards": "Solo se admiten tarjetas emitidas en Corea habilitadas para pagos recurrentes de Toss. El periodo y el importe en KRW aparecen en la confirmación.",
    "inbox.eyebrow": "Cola privada de revisión", "inbox.title": "Bandeja de conocimiento", "inbox.subtitle": "Revisa borradores enviados de forma explícita desde la conversación de IA conectada. Nada se añade al mapa sin tu aprobación.", "inbox.pendingBatches": "lotes pendientes", "inbox.boundaryTitle": "Límite de aprobación:", "inbox.boundaryBody": "cada fila es un lote enviado explícitamente. Añadir todo solo se aplica a ese lote.", "inbox.cardsAdded": "Se añadieron {count} tarjetas.", "inbox.edgesSkipped": "Se omitieron {count} relaciones por destinos no disponibles, duplicados o ciclos no válidos.", "inbox.edgesSaved": "Se guardaron todas las relaciones aprobadas.", "inbox.emptyTitle": "No hay borradores pendientes", "inbox.emptyBody": "Envía conceptos desde una conversación de IA actual y vuelve aquí para revisarlos.", "inbox.manualNote": "Añadir una nota manual", "inbox.drafts": "{count} borradores", "inbox.requested": "Solicitado: {mode}", "inbox.currentImport": "Importación de la conversación actual", "inbox.isolated": "Esta revisión se limita al lote", "inbox.sourceReference": "Referencia de origen: {reference}", "inbox.received": "Recibido {date}", "inbox.reviewBatch": "Revisar este lote", "inbox.back": "Volver a la bandeja", "inbox.reviewTitle": "Revisar borradores de conocimiento", "inbox.reviewSubtitle": "Edita el contenido y las relaciones antes de añadir tarjetas al grafo privado."
  },
  ar: {
    "nav.knowledgeInbox": "صندوق المعرفة", "nav.adminOps": "عمليات المراقبة",
    "admin.ops": "السعة",
    "ads.cardAria": "بطاقة تدريب برعاية", "ads.sponsored": "برعاية", "ads.afterCards": "بعد {count} بطاقة", "ads.title": "حافظ على تدفق المراجعة.", "ads.body": "افتح الخريطة العامة الكاملة وأزل البطاقات الممولة مع Girapphe Plus. تبقى مفاهيمك الخاصة مجانية.", "ads.plans": "عرض Girapphe Plus", "ads.continue": "متابعة المراجعة",
    "toss.failTitle": "أُلغي تسجيل البطاقة", "toss.failBody": "لم تُنشأ دفعة أو صلاحية اشتراك.", "toss.back": "العودة إلى الاشتراكات", "toss.startError": "تعذر بدء الفوترة المتكررة عبر Toss. تحقق من تسجيل الدخول والإعدادات.", "toss.opening": "جارٍ فتح دفع Toss…", "toss.manageFirst": "أدر اشتراكك الحالي أولًا", "toss.trialButton": "تجربة 14 يومًا ببطاقة كورية · ثم ₩{amount}", "toss.payButton": "ادفع ₩{amount} ببطاقة كورية", "toss.supportedCards": "تُدعم فقط البطاقات الصادرة في كوريا والمفعلة للفوترة المتكررة عبر Toss. تظهر دورة الفوترة والمبلغ بالوون في شاشة التأكيد.",
    "inbox.eyebrow": "قائمة مراجعة خاصة", "inbox.title": "صندوق المعرفة", "inbox.subtitle": "راجع المسودات المرسلة صراحة من محادثة الذكاء الاصطناعي الحالية. لن يضاف شيء إلى خريطتك قبل موافقتك.", "inbox.pendingBatches": "دفعات معلقة", "inbox.boundaryTitle": "نطاق الموافقة:", "inbox.boundaryBody": "كل صف دفعة مرسلة صراحة، وإضافة الكل تنطبق على تلك الدفعة فقط.", "inbox.cardsAdded": "أضيفت {count} بطاقة.", "inbox.edgesSkipped": "تم تخطي {count} علاقة لأن أهدافها غير متاحة أو مكررة أو تنشئ دورة غير صالحة.", "inbox.edgesSaved": "حُفظت كل العلاقات المعتمدة.", "inbox.emptyTitle": "لا توجد مسودات منتظرة", "inbox.emptyBody": "أرسل المفاهيم من محادثة حالية ثم عد لمراجعتها.", "inbox.manualNote": "إضافة ملاحظة يدوية", "inbox.drafts": "{count} مسودة", "inbox.requested": "المطلوب: {mode}", "inbox.currentImport": "استيراد المحادثة الحالية", "inbox.isolated": "هذه المراجعة محصورة في الدفعة", "inbox.sourceReference": "مرجع المصدر: {reference}", "inbox.received": "تم الاستلام {date}", "inbox.reviewBatch": "مراجعة هذه الدفعة", "inbox.back": "العودة إلى صندوق المعرفة", "inbox.reviewTitle": "مراجعة مسودات المعرفة", "inbox.reviewSubtitle": "عدّل المحتوى والعلاقات قبل إضافة البطاقات إلى مخططك الخاص."
  },
  hi: {
    "nav.knowledgeInbox": "ज्ञान इनबॉक्स", "nav.adminOps": "मॉनिटरिंग ऑप्स",
    "admin.ops": "क्षमता",
    "ads.cardAria": "प्रायोजित अभ्यास कार्ड", "ads.sponsored": "प्रायोजित", "ads.afterCards": "{count} कार्ड के बाद", "ads.title": "अपनी समीक्षा की लय बनाए रखें।", "ads.body": "Girapphe Plus से पूरा सार्वजनिक मानचित्र खोलें और प्रायोजित कार्ड हटाएँ। आपकी निजी अवधारणाएँ मुफ़्त रहती हैं।", "ads.plans": "Girapphe Plus देखें", "ads.continue": "समीक्षा जारी रखें",
    "toss.failTitle": "कार्ड पंजीकरण रद्द हुआ", "toss.failBody": "कोई भुगतान या सदस्यता अधिकार नहीं बना।", "toss.back": "सदस्यता पर वापस जाएँ", "toss.startError": "Toss आवर्ती भुगतान शुरू नहीं हो सका। साइन-इन और सेटिंग जाँचें।", "toss.opening": "Toss भुगतान खुल रहा है…", "toss.manageFirst": "पहले मौजूदा सदस्यता प्रबंधित करें", "toss.trialButton": "कोरियाई कार्ड से 14 दिन मुफ़्त · फिर ₩{amount}", "toss.payButton": "कोरियाई कार्ड से ₩{amount} भुगतान", "toss.supportedCards": "केवल Toss आवर्ती भुगतान के लिए सक्षम कोरिया में जारी कार्ड समर्थित हैं। बिलिंग अवधि और KRW राशि पुष्टि स्क्रीन पर दिखती है।",
    "inbox.eyebrow": "निजी समीक्षा कतार", "inbox.title": "ज्ञान इनबॉक्स", "inbox.subtitle": "मौजूदा AI बातचीत से स्पष्ट रूप से भेजे गए मसौदों की समीक्षा करें। मंज़ूरी से पहले कुछ भी मानचित्र में नहीं जुड़ता।", "inbox.pendingBatches": "लंबित बैच", "inbox.boundaryTitle": "मंज़ूरी सीमा:", "inbox.boundaryBody": "हर पंक्ति एक स्पष्ट रूप से भेजा बैच है। सभी जोड़ें केवल उसी बैच पर लागू होता है।", "inbox.cardsAdded": "{count} कार्ड जोड़े गए।", "inbox.edgesSkipped": "लक्ष्य अनुपलब्ध, दोहराव या अमान्य चक्र के कारण {count} संबंध सुझाव छोड़े गए।", "inbox.edgesSaved": "सभी स्वीकृत संबंध सहेजे गए।", "inbox.emptyTitle": "कोई मसौदा प्रतीक्षा में नहीं", "inbox.emptyBody": "मौजूदा AI बातचीत से अवधारणाएँ भेजें, फिर यहाँ उनकी समीक्षा करें।", "inbox.manualNote": "इसके बजाय मैनुअल नोट जोड़ें", "inbox.drafts": "{count} मसौदे", "inbox.requested": "अनुरोध: {mode}", "inbox.currentImport": "मौजूदा बातचीत आयात", "inbox.isolated": "यह समीक्षा केवल बैच तक सीमित है", "inbox.sourceReference": "स्रोत संदर्भ: {reference}", "inbox.received": "{date} को मिला", "inbox.reviewBatch": "इस बैच की समीक्षा करें", "inbox.back": "ज्ञान इनबॉक्स पर वापस", "inbox.reviewTitle": "ज्ञान मसौदों की समीक्षा", "inbox.reviewSubtitle": "निजी ग्राफ़ में कार्ड जोड़ने से पहले सामग्री और संबंध संपादित करें।"
  }
} as const;
