// Shared constants, API types, and utilities for web, mobile, and xr apps
// Add shared code here as the project grows

export const APP_NAME = 'Girapphe';

export {
  AD_FREE_ENTITLEMENT_ID,
  BILLING_ENVIRONMENTS,
  BILLING_GRACE_REASONS,
  BILLING_PLANS,
  BILLING_PROVIDERS,
  BILLING_STATUSES,
  BILLING_STORES,
  aggregateAdFreeEntitlement,
  hasDuplicateQualifyingSubscriptions,
  managementDestinationFor,
  subscriptionGrantsAdFree,
  type BillingEntitlementResponse,
  type BillingEnvironment,
  type BillingGraceReason,
  type BillingManagementDestination,
  type BillingManagementKind,
  type BillingPlan,
  type BillingProvider,
  type BillingStatus,
  type BillingStore,
  type CanonicalSubscription,
} from './billing';

export {
  MAX_MOBILE_PRACTICE_BODY_BYTES,
  MAX_MOBILE_PRACTICE_CARD_ID_LENGTH,
  MAX_MOBILE_PRACTICE_CURSOR_LENGTH,
  mergePracticeRoundExclusions,
  type MobilePracticeMode,
  type MobilePracticeRequest,
  type MobilePracticeResponse,
  type MobilePracticeStats,
} from './mobile-practice';

export {
  DEFAULT_LOCALE,
  LOCALE_COOKIE_NAME,
  LOCALE_META,
  SUPPORTED_LOCALES,
  getLocaleDirection,
  getLocaleFromPathname,
  isSupportedLocale,
  localizePathname,
  parseAcceptLanguage,
  resolveLocale,
  stripLocaleFromPathname,
  type Locale,
  type LocaleDirection,
} from './locale';

export {
  DOMAIN_NAMES,
  localizeDomain,
  localizeLevel,
  localizeType,
} from './taxonomy';

export {
  KNOWLEDGE_BUNDLE_SCHEMA_VERSION,
  KNOWLEDGE_BUNDLE_TYPES,
  EVENT_TIME_PRECISIONS,
  createEmptyKnowledgeBundleContent,
  createKnowledgeBundleContentFromLegacy,
  historicalTimePointKey,
  knowledgeBundleRowUsesJsonSyntax,
  isKnowledgeLanguageTag,
  isKnowledgeBundleType,
  parseComparisonCriteriaRows,
  parseExpressionBundleExamples,
  parseStructureComponentRows,
  parseStructureRelationRows,
  parseStringTuplePairs,
  projectKnowledgeBundleContent,
  serializeComparisonCriteriaRows,
  serializeExpressionBundleExamples,
  serializeStructureComponentRows,
  serializeStructureRelationRows,
  serializeStringTuplePairs,
  type ClaimEvidenceBundleContent,
  type ComparisonBundleContent,
  type ConceptBundleContent,
  type DecisionBundleContent,
  type EventChronology,
  type EventBundleContent,
  type EventTimePrecision,
  type ExpressionBundleContent,
  type ExpressionBundleExample,
  type HistoricalTimePoint,
  type KnowledgeBundleContent,
  type KnowledgeBundleType,
  type KnowledgeBundleV1,
  type MechanismBundleContent,
  type ProcedureBundleContent,
  type QuestionBundleContent,
  type StructureBundleContent,
} from './knowledge-bundles';

export {
  hasKnowledgeNotation,
  knowledgeTextRequiresBlockContainer,
  parseKnowledgeText,
  type KnowledgeTextToken,
  type ParseKnowledgeTextOptions,
} from './knowledge-text';

export {
  RECALL_D1_INITIAL_DELIVERY_CLOSE_MS,
  RECALL_D1_OPEN_MS,
  RECALL_D7_CLOSE_MS,
  RECALL_D7_OPEN_MS,
  RECALL_POST_D7_INTERVAL_MS,
  RECALL_SNOOZE_MS,
  RECALL_SUPPORTED_BUNDLE_TYPES,
  assessRecallSchedule,
  classifyRecallWindow,
  createRecallEnrollmentSchedule,
  getRecallBoundaries,
  isRecallSupportedBundleType,
  requestRecallSnooze,
  rescheduleUnopenedRecall,
  rollRecallWindow,
  type RecallAssessmentOutcome,
  type RecallD7Outcome,
  type RecallInstant,
  type RecallPracticeProjection,
  type RecallScheduleDecision,
  type RecallScheduleSnapshot,
  type RecallScheduleState,
  type RecallSnoozeDecision,
  type RecallSupportedBundleType,
  type RecallWindow,
} from './recall-schedule';
